//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UR3eHande
{
    [Serializable]
    public class UR3eStateMsg : Message
    {
        public const string k_RosMessageName = "ur3e_hande_controller/UR3eState";
        public override string RosMessageName => k_RosMessageName;

        public double[] joints;
        public double[] fingers;

        public UR3eStateMsg()
        {
            this.joints = new double[6];
            this.fingers = new double[1];
        }

        public UR3eStateMsg(double[] joints, double[] fingers)
        {
            this.joints = joints;
            this.fingers = fingers;
        }

        public static UR3eStateMsg Deserialize(MessageDeserializer deserializer) => new UR3eStateMsg(deserializer);

        private UR3eStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joints, sizeof(double), 6);
            deserializer.Read(out this.fingers, sizeof(double), 1);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joints);
            serializer.Write(this.fingers);
        }

        public override string ToString()
        {
            return "UR3eStateMsg: " +
            "\njoints: " + System.String.Join(", ", joints.ToList()) +
            "\nfingers: " + System.String.Join(", ", fingers.ToString());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
