//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UR3eHande
{
    [Serializable]
    public class UR3eTargetsMsg : Message
    {
        public const string k_RosMessageName = "ur3e_hande_controller/UR3eTargets";
        public override string RosMessageName => k_RosMessageName;

        public double[] targets;
        public Geometry.PoseMsg redBall1_pickPose;
        public Geometry.PoseMsg redBall2_pickPose;
        public Geometry.PoseMsg blueBall1_pickPose;
        public Geometry.PoseMsg blueBall2_pickPose;
        public Geometry.PoseMsg redBall_placePose;
        public Geometry.PoseMsg blueBall_placePose;

        public UR3eTargetsMsg()
        {
            this.targets = new double[6];
            this.redBall1_pickPose = new Geometry.PoseMsg();
            this.redBall2_pickPose = new Geometry.PoseMsg();
            this.blueBall1_pickPose = new Geometry.PoseMsg();
            this.blueBall2_pickPose = new Geometry.PoseMsg();
            this.redBall_placePose = new Geometry.PoseMsg();
            this.blueBall_placePose = new Geometry.PoseMsg();
        }

        public UR3eTargetsMsg(double[] targets, Geometry.PoseMsg redBall1_pickPose, Geometry.PoseMsg redBall2_pickPose, Geometry.PoseMsg blueBall1_pickPose, Geometry.PoseMsg blueBall2_pickPose, Geometry.PoseMsg redBall_placePose, Geometry.PoseMsg blueBall_placePose)
        {
            this.targets = targets;
            this.redBall1_pickPose = redBall1_pickPose;
            this.redBall2_pickPose = redBall2_pickPose;
            this.blueBall1_pickPose = blueBall1_pickPose;
            this.blueBall2_pickPose = blueBall2_pickPose;
            this.redBall_placePose = redBall_placePose;
            this.blueBall_placePose = blueBall_placePose;
        }

        public static UR3eTargetsMsg Deserialize(MessageDeserializer deserializer) => new UR3eTargetsMsg(deserializer);

        private UR3eTargetsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.targets, sizeof(double), 6);
            this.redBall1_pickPose = Geometry.PoseMsg.Deserialize(deserializer);
            this.redBall2_pickPose = Geometry.PoseMsg.Deserialize(deserializer);
            this.blueBall1_pickPose = Geometry.PoseMsg.Deserialize(deserializer);
            this.blueBall2_pickPose = Geometry.PoseMsg.Deserialize(deserializer);
            this.redBall_placePose = Geometry.PoseMsg.Deserialize(deserializer);
            this.blueBall_placePose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.targets);
            serializer.Write(this.redBall1_pickPose);
            serializer.Write(this.redBall2_pickPose);
            serializer.Write(this.blueBall1_pickPose);
            serializer.Write(this.blueBall2_pickPose);
            serializer.Write(this.redBall_placePose);
            serializer.Write(this.blueBall_placePose);
        }

        public override string ToString()
        {
            return "UR3eTargetsMsg: " +
            "\ntargets: " + System.String.Join(", ", targets.ToList()) +
            "\nredBall1_pickPose: " + redBall1_pickPose.ToString() +
            "\nredBall2_pickPose: " + redBall2_pickPose.ToString() +
            "\nblueBall1_pickPose: " + blueBall1_pickPose.ToString() +
            "\nblueBall2_pickPose: " + blueBall2_pickPose.ToString() +
            "\nredBall_placePose: " + redBall_placePose.ToString() +
            "\nblueBall_placePose: " + blueBall_placePose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
