//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UR3eHande
{
    [Serializable]
    public class UR3eTrajectoryRTAMsg : Message
    {
        public const string k_RosMessageName = "ur3e_hande_controller/UR3eTrajectoryRTA";
        public override string RosMessageName => k_RosMessageName;

        public Std.StringMsg group;
        public Moveit.RobotTrajectoryMsg trajectory;

        public UR3eTrajectoryRTAMsg()
        {
            this.group = new Std.StringMsg();
            this.trajectory = new Moveit.RobotTrajectoryMsg();
        }

        public UR3eTrajectoryRTAMsg(Std.StringMsg group, Moveit.RobotTrajectoryMsg trajectory)
        {
            this.group = group;
            this.trajectory = trajectory;
        }

        public static UR3eTrajectoryRTAMsg Deserialize(MessageDeserializer deserializer) => new UR3eTrajectoryRTAMsg(deserializer);

        private UR3eTrajectoryRTAMsg(MessageDeserializer deserializer)
        {
            this.group = Std.StringMsg.Deserialize(deserializer);
            this.trajectory = Moveit.RobotTrajectoryMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.group);
            serializer.Write(this.trajectory);
        }

        public override string ToString()
        {
            return "UR3eTrajectoryRTAMsg: " +
            "\ngroup: " + group.ToString() +
            "\ntrajectory: " + trajectory.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
