//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UR3eHande
{
    [Serializable]
    public class UR3ePickAndPlaceRequest : Message
    {
        public const string k_RosMessageName = "ur3e_hande_controller/UR3ePickAndPlace";
        public override string RosMessageName => k_RosMessageName;

        public UR3eTargetsMsg targets_input;
        public Geometry.PoseMsg redBall1_pickPose;
        public Geometry.PoseMsg redBall2_pickPose;
        public Geometry.PoseMsg blueBall1_pickPose;
        public Geometry.PoseMsg blueBall2_pickPose;
        public Geometry.PoseMsg redBall_placePose;
        public Geometry.PoseMsg blueBall_placePose;

        public UR3ePickAndPlaceRequest()
        {
            this.targets_input = new UR3eTargetsMsg();
            this.redBall1_pickPose = new Geometry.PoseMsg();
            this.redBall2_pickPose = new Geometry.PoseMsg();
            this.blueBall1_pickPose = new Geometry.PoseMsg();
            this.blueBall2_pickPose = new Geometry.PoseMsg();
            this.redBall_placePose = new Geometry.PoseMsg();
            this.blueBall_placePose = new Geometry.PoseMsg();
        }

        public UR3ePickAndPlaceRequest(UR3eTargetsMsg targets_input, Geometry.PoseMsg redBall1_pickPose, Geometry.PoseMsg redBall2_pickPose, Geometry.PoseMsg blueBall1_pickPose, Geometry.PoseMsg blueBall2_pickPose, Geometry.PoseMsg redBall_placePose, Geometry.PoseMsg blueBall_placePose)
        {
            this.targets_input = targets_input;
            this.redBall1_pickPose = redBall1_pickPose;
            this.redBall2_pickPose = redBall2_pickPose;
            this.blueBall1_pickPose = blueBall1_pickPose;
            this.blueBall2_pickPose = blueBall2_pickPose;
            this.redBall_placePose = redBall_placePose;
            this.blueBall_placePose = blueBall_placePose;
        }

        public static UR3ePickAndPlaceRequest Deserialize(MessageDeserializer deserializer) => new UR3ePickAndPlaceRequest(deserializer);

        private UR3ePickAndPlaceRequest(MessageDeserializer deserializer)
        {
            this.targets_input = UR3eTargetsMsg.Deserialize(deserializer);
            this.redBall1_pickPose = Geometry.PoseMsg.Deserialize(deserializer);
            this.redBall2_pickPose = Geometry.PoseMsg.Deserialize(deserializer);
            this.blueBall1_pickPose = Geometry.PoseMsg.Deserialize(deserializer);
            this.blueBall2_pickPose = Geometry.PoseMsg.Deserialize(deserializer);
            this.redBall_placePose = Geometry.PoseMsg.Deserialize(deserializer);
            this.blueBall_placePose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.targets_input);
            serializer.Write(this.redBall1_pickPose);
            serializer.Write(this.redBall2_pickPose);
            serializer.Write(this.blueBall1_pickPose);
            serializer.Write(this.blueBall2_pickPose);
            serializer.Write(this.redBall_placePose);
            serializer.Write(this.blueBall_placePose);
        }

        public override string ToString()
        {
            return "UR3ePickAndPlaceRequest: " +
            "\ntargets_input: " + targets_input.ToString() +
            "\nredBall1_pickPose: " + redBall1_pickPose.ToString() +
            "\nredBall2_pickPose: " + redBall2_pickPose.ToString() +
            "\nblueBall1_pickPose: " + blueBall1_pickPose.ToString() +
            "\nblueBall2_pickPose: " + blueBall2_pickPose.ToString() +
            "\nredBall_placePose: " + redBall_placePose.ToString() +
            "\nblueBall_placePose: " + blueBall_placePose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
