//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UR3eHande
{
    [Serializable]
    public class UR3ePickAndPlaceRTARequest : Message
    {
        public const string k_RosMessageName = "ur3e_hande_controller/UR3ePickAndPlaceRTA";
        public override string RosMessageName => k_RosMessageName;

        public UR3eStateMsg state;
        public UR3eTargetMsg ball;
        public UR3eTargetMsg basket;

        public UR3ePickAndPlaceRTARequest()
        {
            this.state = new UR3eStateMsg();
            this.ball = new UR3eTargetMsg();
            this.basket = new UR3eTargetMsg();
        }

        public UR3ePickAndPlaceRTARequest(UR3eStateMsg state, UR3eTargetMsg ball, UR3eTargetMsg basket)
        {
            this.state = state;
            this.ball = ball;
            this.basket = basket;
        }

        public static UR3ePickAndPlaceRTARequest Deserialize(MessageDeserializer deserializer) => new UR3ePickAndPlaceRTARequest(deserializer);

        private UR3ePickAndPlaceRTARequest(MessageDeserializer deserializer)
        {
            this.state = UR3eStateMsg.Deserialize(deserializer);
            this.ball = UR3eTargetMsg.Deserialize(deserializer);
            this.basket = UR3eTargetMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
            serializer.Write(this.ball);
            serializer.Write(this.basket);
        }

        public override string ToString()
        {
            return "UR3ePickAndPlaceRTARequest: " +
            "\nstate: " + state.ToString() +
            "\nball: " + ball.ToString() +
            "\nbasket: " + basket.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
